async function runTests() {
  console.log('Running e2e-tests')
  console.log('Finished e2e-tests')
}

runTests().catch((err) => console.error(err))
